Env: "dev"

DatabaseSettings:
  DatabaseURI: "root:Atonng...@tcp(localhost:3306)/go_database?parseTime=True&loc=Local"
  DatabaseName: "go_database"
  Username: "root"
  Password: "Atonng..."


JwtSettings:
  SecretKey: "golang-tech-stack"

